server:
  port: 8081

spring:
  application:
    name: CUSTOMER
  datasource:
    url: jdbc:postgresql://customer-db:5431/customer
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        use_sql_comments: true
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
  flyway:
    baseline-on-migrate: true
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

info:
  app:
    name: Customer-microservice
